### ISSUE TITLE
AngularJS demo doesn't work in Chrome v.31.0.1650.63 on Windows 8

### ISSUE THREAD

**Issue by schmoofer** [zohararad/audio5js#27]
AngularJS demo doesn't work in Chrome v.31.0.1650.63 on Windows 8, but works with Firefox and IE

**Comment by kamijoutouma** [comment]
@zohararad 2 year old issue?

**Comment by zohararad** [comment]
yeah. we can safely close it, since the guy who wrote the angular demo ditched it

**Comment by altryne** [comment]
I did, didn't I? sorry bro :(
