### ISSUE TITLE
Issue testing angular demo

### ISSUE THREAD

**Issue by x20mar** [zohararad/audio5js#37]
Hi, 

I'm trying to run the angular demos but on both of them I get the following error

    Error: this.audio is undefined
    FlashAudioPlayer.prototype.play@file:///home/lucy/Downloads/audio5js-master/src/audio5.js:430
    Audio5js.prototype.play@file:///home/lucy/Downloads/audio5js-master/src/audio5.js:828
    Audio5js.prototype.playPause@file:///home/lucy/Downloads/audio5js-master/src/audio5.js:843
    Mc/u/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.min.js:70
    dc[c]</</</<@http://ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.min.js:141
    Sc/this.$get</e.prototype.$eval@http://ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.min.js:86
    Sc/this.$get</e.prototype.$apply@http://ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.min.js:86
    dc[c]</</<@http://ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.min.js:140
    pc/c/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.min.js:22
    m@http://ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.min.js:6
    pc/c@http://ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.min.js:22
    "

Also on a side note is there anyway to state that you don't want a flash fallback?

Thanks

**Comment by kamijoutouma** [comment]
@zohararad this issue looks to have been resolved but you never closed it.

**Comment by zohararad** [comment]
must've missed it @kamijoutouma closing now (thanks for your help in cleaning up things)

**Comment by kamijoutouma** [comment]
No problem ;)
