### ISSUE TITLE
Audio not playing on iOS 8 standalone web app

### ISSUE THREAD

**Issue by 1auralynn** [zohararad/audio5js#51]
Audio which plays as expected on iOS7 in safari and as a web app that is 'saved to homescreen' does not play on iOS8 in the homescreen version. Works fine in Safari and all other desktop browsers.

It's likely a known bug w/ iOS8 but thought I would put here in case anyone has insight. http://stackoverflow.com/questions/25977730/video-no-longer-playing-in-ios-8-webbapp-standalone-mode-anyone-found-a-solutio

**Comment by ydaniv** [comment]
@zohararad I stumbled on this one before, are you still working on this?

**Comment by zohararad** [comment]
@ydaniv not actively.... would love to hear your thoughts / solutions

**Comment by 1auralynn** [comment]
After many months of looking into this issue, it's a bug on Apple's end,
and there is no workaround. Check the apple dev forums for more info.

On Wed, Aug 19, 2015 at 1:10 PM, zohararad <notifications@github.com> wrote:

> @ydaniv <https://github.com/ydaniv> not actively.... would love to hear
> your thoughts / solutions
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zohararad/audio5js/issues/51#issuecomment-132764950>.
>



-- 
Partner, Dynamoid Apps
dynamoidapps.com

**Comment by ydaniv** [comment]
Yes, correct. Now I recall we updated to iOS 8.3 and it resolved the issue.
בתאריך 19 באוג׳ 2015 23:16,‏ "Laura Lynn Gonzalez" <notifications@github.com>
כתב:

**Comment by zohararad** [comment]
marking this is closed
