### ISSUE TITLE
Audio5js on mobile browsers

### ISSUE THREAD

**Issue by franz976** [zohararad/audio5js#58]
Hi, I'd like to use audio5js on a playlist-site (hvsr.net) but I'm experiencing some problems on mobile browsers. I know Apple and Android won't allow the autoplay feature, and it's ok for me to have the playlist streamed only after the user plays the PLAY button. BUT I would like the player to stream a new song when the previous one has ended. On desktop it works, but not on mobile. Please take a look at  this demo page:
http://jsfiddle.net/franz976/pyt5k0ma/

thank you

**Comment by zohararad** [comment]
@franz976 I think the obstacle here is that interacting with the Audio element on mobile requires explicit user interaction.

Maybe the solution is to stream your playlist using something like Shoutcast rather than try to load new files on end. I realise its annoying but it's a limitation of the mobile platforms rather than Audio5js.

Just as a side-note, Audio5 works nicely with Shoutcast (was one of the original purposes for which I built the library)

**Comment by franz976** [comment]
Thanks @zohararad. I wonder what kind of player use the folks at http://www.indieshuffle.com, cause it's pretty the same thing I want to reach...

**Comment by zohararad** [comment]
From a quick peak at their code, they have their own HTML5 player (I think). Maybe they found a way around the auto-play issue on mobile

**Comment by pteich** [comment]
Indie Shuffle uses SoundManager 2 (http://www.schillmania.com/projects/soundmanager2/)
The problem with Audio5js probably is that on every load of a new file it destroys an existing audio object and creates an new one. This is necessary for playing streaming media (Icecast/Shoutcast) otherwise some browsers won't stop loading data of the old stream if you switch to a new one. (I use Audio5js just like @zohararad to play Icecast mp3 streams and ran into this.)
But this recreation of audio objects seems to trigger iOS to request user interaction on every new file load. Sound Manager 2 maybe re-uses an existing audio object.

**Comment by zohararad** [comment]
@pteich that might be a very valid insight. I'll try and see if I can re-use the audio object

**Comment by ErikAGriffin** [comment]
Yes I'm very glad you fixed this with Audio5js.  Playing through a playlist on mobile browsers is possible by swapping out the source of the audio after a click event has initiated play()  (*as described in [this stack answer](http://stackoverflow.com/a/21294015/1739675)*). It works amazing.

However I have run into a new problem, which can hopefully be solved. I am not yet familiar enough with Audio5 to investigate on my own. If one of the song steam url's fails to load, thus triggering the 'error' event, the auto / continuous play stops working.  Are you destroying the audio object on error? Here is my app's current flow:

Click play event -> song ended -> load(newUrl) -> play()  ... 
load(newUrl) -> **fails** -> errorEvent -> load(newUrl) -> play()...

Again, after the error event the audio does not play on mobile, but works fine in the browser. Furthermore (not sure how related this is)  my object.playing reports **true**, and calling object.pause() has absolutely not effect (the state of object.playing remains true).

**Comment by zohararad** [comment]
@ErikAGriffin looking at the code again, the audio object isn't destroyed on playback / load errors. The behaviour is to escalate the error to the implementation where it should be handled.

There is a config setting that controls whether the error is thrown or not ( see [L994](https://github.com/zohararad/audio5js/blob/master/src/audio5.js#L994) )

I'd try to first check whether an error is thrown and not caught, which might explain the breakage. I'm not familiar enough with mobile browsers internals to confirm if an audio load error might break the "legitimate click event cycle", but perhaps the solution would be to simply display a notification to the user that the audio cannot be loaded and that they should click to continue

**Comment by ErikAGriffin** [comment]
Hm my `throw_errors`property is false, so I just have the `object.on('error')` function I am working with. Is there something specific I may need to be doing within that function?

Unfortunately the whole purpose of my application is that someone would be far away from their phone, so having to go and click play again and unknown intervals is not a real option.  One fix I have considered is having a separate player object that attempts to load all songs before they are actually loaded into the player which receives the click event.  If the secondary player object gets an error, it sets a boolean that causes the active player to not attempt to load that song.

Not perfect and may not work, but just my thoughts

**Comment by ErikAGriffin** [comment]
So tinkering around today with raw HTML5 audio, when an error event was triggered I was able to load and continue autoplay on mobile Safari no problem, so it is something within Audio5js that is causing this to break. I'll continue investigating

**Comment by zohararad** [comment]
@ErikAGriffin thanks. I'll look forward to hearing if you found anything

**Comment by pteich** [comment]
I know that it's really a pain to get that audio thing right on mobile devices. I had to put a lot of afford in this. What works for me for your specific issue is something like this (stripped down to only interesting parts):

````

        var audio5js;

         audio5js = new Audio5js({
                throw_errors: false,
                ready: function () {
                    this.on('error', function(err) {
                        console.log(er.message);
                        playFile(url);
                    });
                }
            });
       

        function playFile(url) {

            audio5js.one('canplay', function () {
                audio5js.play();
            });

            if (audio5js.playing) {
                audio5js.one('pause', function () {
                    audio5js.load(url);
                });
                audio5js.pause();
            } else {
                audio5js.load(url);
            }

        }
```

First play is of course triggered by e.g. a button that executes playFile(). But if an error occurs after this, it plays a new url without forcing the user to interact again. Not sure, if this helps you.

**Comment by ErikAGriffin** [comment]
Although I do not fully understand the structure of Audio5js, I was able to return the functionality described above on mobile safari after adding just a single line of a code to the audio5.js source.  However before I submit a pull request, I have a question:

Why do events trigger for both the html5 player object in the Audio5js object (aka `myAudio5obj.audio`) AND the Audio5js object itself?  Why two whole sets of event listeners?  Secondly, and this is more curiosity, why do both objects have a **.playing** property?  It seems to me that only the Audio5js object's **.playing** property gets used.

@zohararad

**Comment by zohararad** [comment]
@ErikAGriffin 

Thanks for digging through the code. The idea behind events in Audio5 is that the escalate from the Audio engines (HTML5 / Flash) to the Audio5 object which you instantiate. That's why there's a chain of events.

If you want to submit a PR, please fork the repo, add your code, push to your GH account and then send a PR via Github. Please make sure the tests pass if you can.

**Comment by ErikAGriffin** [comment]
Hmm I was unable to run grunt as the uglify build task threw a warning: `Warning: Cannot assign to read only property 'subarray' of ...` then shows the entire minified code.  However trying the same on a cloned repo of the original achieved the same result, so perhaps I have not set something up correctly.

However I did run Mocha tests by opening the tests.html and everything passed. Submitting the pull request now

**Comment by zohararad** [comment]
@ErikAGriffin please delete irrelevant PRs and resend the latest PRs so there's no mixup

**Comment by ErikAGriffin** [comment]
@zohararad  Done and done.

**Comment by zohararad** [comment]
Thanks. Merged

**Comment by ErikAGriffin** [comment]
This is still only merged in the /src and not on the root release and minified build

**Comment by zohararad** [comment]
@ErikAGriffin sorry about that - built and pushed
