### ISSUE TITLE
The demo is not working in IE8

### ISSUE THREAD

**Issue by AdamFu** [zohararad/audio5js#59]
View th demo link:http://zohararad.github.com/audio5js/
Use IE11,It's work.But in IE8 simulation mode，don't work.
![1](https://cloud.githubusercontent.com/assets/5377868/5987020/f2049b42-a950-11e4-9ac1-7f8219be4f1e.jpg)

**Comment by zohararad** [comment]
Thanks - will check it out

**Comment by zohararad** [comment]
@AdamFu should work in IE8 now (latest code wasn't merged to gh-pages branch)
