### ISSUE TITLE
Position is 0 after Seek, then Play.

### ISSUE THREAD

**Issue by leonardorame** [zohararad/audio5js#61]
Hi, I can play() an mp3 file, then seek(), and monitor it's position using the timeupdate event. This works as expected.

My problem is the position returns to 0 when I do this process:

1: pause()
2: seek(position + 0.5) // advance the position 1/2 second
3: play()

Imagine the position at 1 is 10 seconds and duration is 20 seconds. After step 2, the position pointer is 10.5 seconds, then, on step 3, the position should remain there, but it returns to 0. Is this a bug?.

**Comment by zohararad** [comment]
I'm not sure. It could be any one of several things. Here's what i'd suggest you try checking:

1. Check with another file - Maybe the file you're using is badly encoded
2. Check with HTML5 audio directly - Although this part of the library works directly with the HTML5 api, it's worth checking to eliminate any hidden bugs
3. Check on several browsers

**Comment by leonardorame** [comment]
I tried with the same file:

FF 35.0.1 64bits linux it works ok
IE 8 32bit works ok (swf).
Chrome 40.0.2214.111 (64-bit) does not work.

I can send a sample file to let you test it.

**Comment by zohararad** [comment]
Did you also try using the HTML5 audio api directly? This might be a Chrome-specific issue...

**Comment by leonardorame** [comment]
Aparently the problem is related to the files I'm playing. 

I tested this jsfiddle on chrome and it works ok: http://jsfiddle.net/aarongloege/fzXsT/light/

But, when I replace the sample files with my own, I can play, but not seek.

My files originally are WAV and I convert on the fly to MP3 using lame. I don't think the problem is this.

I also noted some differences in the headers returned by the examples from the jsfiddle and my onwn:

Here are the headers my server returns:

    Connection:Keep-Alive
    Content-Length:22680
    Content-Type:audio/mpeg
    Date:Sun, 22 Feb 2015 11:24:32 GMT
    Keep-Alive:timeout=5, max=93
    Server:Apache/2.2.22 (Ubuntu)
    X-Powered-By:Brook framework and FCL-Web.

And here are the headers from the jsfiddle examples:

    cache-control:no-cache
    Connection:keep-alive
    Content-Type:text/html; charset=utf-8
    Date:Sun, 22 Feb 2015 11:45:49 GMT
    location:http://dl.dropboxusercontent.com/u/1538714/article_resources/song.m4a
    pragma:no-cache
    Server:nginx
    Transfer-Encoding:chunked
    X-Robots-Tag:noindex, nofollow, noimageindex

The obvious difference is they send chunked data and I use Content-Length.

**Comment by zohararad** [comment]
Ok, thanks for sharing. In that case, I'll mark this issue as closed
