### ISSUE TITLE
How to integrate with backbone js

### ISSUE THREAD

**Issue by deepugn** [zohararad/audio5js#62]
Could you please help me integrate audio5js with backbone js. I am using handlebars templates, i need to put audio to my backbone view, as internet explorer wont play .wav files.

Sorry, this is not an issue, was just asking a help :) .

Best Regards,
Deepu.

**Comment by zohararad** [comment]
Hmmm.. am not a backbone expert, but it seems to me like you need to capture click events on your view (or is it controller in Backbone) and pass them on to a global Audio5js instance

**Comment by kamijoutouma** [comment]
@zohararad Im no backbone expert either But this question is a bit old and is not actually an issue so i'm gonna @ them if they don't respond within 24-48 hours can you close this.
@deepugn Have you found a way to implement what you were trying to do?

**Comment by zohararad** [comment]
Yeah... same as the Angular stuff. Am closing this as it falls outside the domain of Audio5js. @deepugn feel free to post here if you wish to discuss and reopen the issue
