### ISSUE TITLE
How to set swf path in angularjs service

### ISSUE THREAD

**Issue by brenthmiras** [zohararad/audio5js#64]
TheAudioService can be easily injected in any controller or service but how can the audio instance initialization parameters (i.e. swfPath) be set?

**Comment by zohararad** [comment]
@brenthmiras I actually can't answer that as I'm not the author of the Angluar example code, and I'm not an Angular developer.

I'd be happy to accept a PR if you sort it out

**Comment by kamijoutouma** [comment]
@brenthmiras Any luck?
@zohararad same as the last one xD

**Comment by zohararad** [comment]
I'm going to close this one - Angular demo is a bit sketchy and I think it should be solved outside the domain of Audio5js. @brenthmiras if you have any objections, please feel free to post them and I'll reopen

**Comment by ahmed-wagdi** [comment]
This isn't an angular issue, i've been trying to trace this problem and there seems to be a problem with the `onTimeUpdate` function. The position property is formatted every time the time update event is triggered but the duration property is in an if condition:
```
if (this.duration !== duration) {
  this.duration = this.settings.format_time && duration !== null ? util.formatTime(duration) : duration;
}
```
This condition never evaluates to true so the duration never gets formatted.
