### ISSUE TITLE
play() can only run once in safari without quicktime

### ISSUE THREAD

**Issue by speedneeder** [zohararad/audio5js#65]
this is a simple html:

		<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
		<head>
		  <script src="js/audio5.js"></script>
		  <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
		</head>

		<body>
		  <button id="play">play</button>

		  
		  
		  <script type="text/javascript">
		    $(document).ready(function(){
		      var audio5js = new Audio5js({
		        swf_path: 'swf/audio5js.swf',
		        ready: function () {
		          this.load('sample3.mp3');
		        }
		      });

		      $("#play").click(function(){
		       audio5js.play();
		     });

		    });
		  </script>
		</body>

		</html>

I open it in safari without quicktime on my pc(so the mp3 will play with audio5js.swf, I think), and I click the play button, the mp3 will play, it works. But when I press the button again, it is no sound.

I open this html with firefox and ie, audio5js works well.

what's wrong? it seems like the swf is not correct run at the second time.

**Comment by zohararad** [comment]
Not sure... Did you say you're running Safari on Windows? That's pretty rare. What version of Flash are you using?

**Comment by newpxsn** [comment]
The Windows version of Safari was discontinued in May 9, 2012. This should closed.

**Comment by kamijoutouma** [comment]
yeah this should definitely be closed. Also flash has become sort of obsolete. And is technically always insecure especially now that almost no one uses it since html5 came out. I can't wait till flash support is completely dropped in all browsers once html5 reaches its full potential.

**Comment by zohararad** [comment]
perfect!
