### ISSUE TITLE
Completely remove all Flash components

### ISSUE THREAD

**Issue by iFlash** [zohararad/audio5js#69]
Hello,

is it possible to use audio5js in a way that no flash components are used at all. Because even if the html player is used, it seems there is an SWF pixel generated. I realized this through Google Page Speed Inisghts. 

So  the question: Is there a way to have audio5js purely use html and nothing else?

**Comment by zohararad** [comment]
You should be able to pass `use_flash: false` to the settings object. If it doesn't work please write back and i'll check why

**Comment by iFlash** [comment]
I will check for that and let you know. Meanwhile I ran into an even bigger problem:

I am generating several players on a page with a rail, so people can seek. But the seek does not work. The click is triggered, but audio.seek will stop playing the audio instead of seeking. Afterwards I can not play the audio anymore at all.

Any help would be highly appreciated!

This is what I do:
````
$.fn.bplayer=function() {
	that = this;
	var audio5;
	var buttonPlay=$(this);
	var source=$(this).data("audio");
	var state=$(this).find("i");
	var	progress=$(this).closest('.player').find('.progress');
	var	rail=$(this).closest('.player').find('.rail');
	
	audio5 = new Audio5js({
		swf_path:'./swf/audio5js.swf',
		ready:function () {
			this.on('seeking', audioSeeking, this);
			this.on('canplay', playPause, this);
			this.on('ended', audioEnded, this);
			this.on('progress', function(load_percent) {
				// here goes the load progress if needed
			}, this);
			this.on('timeupdate', function(position, duration) {
				var tmp=position.split(':').reverse(),
					secs=parseInt(tmp[0])+
						(tmp.length>1?tmp[1]*60:0)+
						(tmp.length>2?tmp[2]*60*60:0);
				progress.css('width',(100*secs/duration)+'%');
				progress.css('transition','.25s ease all');
			}, this);
			
			buttonPlay.on('click', loadAudio);
		}
	});

	function loadAudio () {
		buttonPlay.off('click', loadAudio);
		state.removeClass('fa-play').addClass('fa-spinner fa-spin');
		buttonPlay.on('click',playPause.bind(audio5));
		audio5.load(source);
		rail.on('click', function(e) {
			console.log("Rail clicked");
			var ofs=e.pageX-rail.offset().left;
			audio5.seek(audio5.duration*ofs/rail.width());
		});
	}

	function playPause () {
		if (this.playing) {
			this.pause();
			buttonPlay.removeClass('playing');
			state.removeClass('fa-spinner fa-spin fa-pause');
			state.addClass('fa-play');
		} else {
			$('.player button').each(function() {
				if ($(this).hasClass('playing'))
					$(this).click();
			});
			this.play();
			state.removeClass('fa-spinner fa-spin fa-play');
			state.addClass('fa-pause');
			buttonPlay.addClass('playing');
		}
	}

	function audioSeeking () {
		this.seek(0);
	}

	function audioEnded () {
		var self=this;
		this.seek(0);
		setTimeout(function() {
			self.pause();
			state.addClass('fa-play').removeClass('fa-pause');
			buttonPlay.removeClass('playing');
		}, 50);
	}
};

$(function() {
	$('.player button').each(function() {
		$(this).bplayer();
	});
});
````

The html looks like this (several players will be used)
````
<span class="player">
	<button data-audio="some-mp3.here"><i class="fa fa-play fa-fw"></i></button>
	<span class="rail"><span class="progress"></span></span>
</span>
...
<span class="player">
	<button data-audio="some-other-mp3.here"><i class="fa fa-play fa-fw"></i></button>
	<span class="rail"><span class="progress"></span></span>
</span>
````

**Comment by iFlash** [comment]
Regarding Flash: No, that did not the trick. Page Speed still claims I use plug ins like this:

http://domain.com/swf/audiojs.swf?playerInstance=window.Audio5js_flash.instances['Audio5js1']&datetime=1437734808886.3787

But I don't know what google is referring to.

**Comment by zohararad** [comment]
Ok - let me check this. Do you have any insights into which browsers are triggering the Flash plugin?

**Comment by zohararad** [comment]
@iFlash sorry for taking a bit long to check this. I did another check on my PC and setting use_flash to false will not embed the Flash player. If you can provide a few more details on which browsers seem to use Flash according to Google Pagespeed I Can try and look deeper

**Comment by iFlash** [comment]
That's strange. I used it with Safari. But, of course, what I, myself use as a browser is of no interest, as it was Google's bot that still found the sfx pixel. I am not sure which User Agent they use.

**Comment by iFlash** [comment]
As a temp fix I simply removed all flash components our of the source code. I believe that flash should not be used at all anyway (not even as fallback), so that's fine for me. Still, it would be a nice improvement to your code, if the user can 100 per cent prevent the use of any flash at all no matter which browser is detected.

**Comment by zohararad** [comment]
@iFlash you can try setting the swf path to null and that will of course prevent embedding flash at all.

As for Flash support as fallback, regardless of the recent flames regarding the usefulness / security risks of Flash, I still think it's a good thing to have in the browser-based audio realm since browser support for various codecs is horrible.

I'll take another look and see if I can find why Flash was embedded by Google bot with the use_flash:false flag

**Comment by kamijoutouma** [comment]
@zohararad which codecs? I can probably link you to library's that can decode these codecs without issues or excessive load on the client. This however would require a bit of rewriting just letting you know.

**Comment by zohararad** [comment]
The main reason for using Flash was to provide cross-platform MP3 support, which is still the most widely used audio format.

Although newer browsers do support MP3, some people still require backwards compatibility in older browsers, either without MP3 support or without HTML5 audio support, which is where Flash comes in.

If you only need native HTML5 support, for modern codecs, you can simply use HTML5 audio directly
