### ISSUE TITLE
Format Duration not working

### ISSUE THREAD

**Issue by ahmed-wagdi** [zohararad/audio5js#71]
I'm using audio5js with angular and for some reason format_time only affects position but duration always remains unformatted in seconds. Also i've checked all the demos for ngAudio and they all seem to have the same problem.

**Comment by zohararad** [comment]
If you look at [L1029](https://github.com/zohararad/audio5js/blob/master/src/audio5.js#L1029) in the source, you'll notice that during requires the audio file to contain that value. Some files (for example streaming) don't have an explicit duration, and therefore it cannot be inferred and formatted.

What kind of audio are you using? (format, stream / download)

**Comment by ahmed-wagdi** [comment]
I am currently streaming the same file that you use in you're demos:
"http://danosongs.com/music/danosongs.com-orb-of-envisage.mp3"

**Comment by zohararad** [comment]
Hmm... my suggestion is to try and use the library without any angular-related logic first, and see if the problem persists. If it does, it might be an issue with the angular implementation.

Btw, are you using the angular demo included in the repo? If you are, then please note its not maintained

**Comment by kamijoutouma** [comment]
@ahmed-wagdi What is the current status of this issue? Have you figured out your problem or does it still exist. 
@zohararad same as the last one ;P

**Comment by ahmed-wagdi** [comment]
@kamijoutouma Not sure if i would call it a fix, it's more like a work around.

I kept the format_time unformatted so that it always returns seconds then added a custom filter with angular to convert seconds into a date object.
```
angular.('myApp', []).filter('secondsToDateTime', function() {
    return function(seconds) {
        var d = new Date(0,0,0,0,0,0,0);
        d.setSeconds(seconds);
        return d;
    };
})
```
After you convert it into a date object you can just use angular's built in filters to set it to whatever format you like (in this case minutes and seconds)

```
{{player.duration | secondsToDateTime | date:'mm:ss'}}
```

**Comment by zohararad** [comment]
I think this one is safe to close

**Comment by ahmed-wagdi** [comment]
This isn't an angular issue, i've been trying to trace this problem and there seems to be a problem with the `onTimeUpdate` function. The position property is formatted every time the time update event is triggered but the duration property is in an if condition:
```
if (this.duration !== duration) {
  this.duration = this.settings.format_time && duration !== null ? util.formatTime(duration) : duration;
}
```
This condition never evaluates to true so the duration never gets formatted.

**Comment by zohararad** [comment]
thanks @ahmed-wagdi pushed a fix for this now
