### ISSUE TITLE
Setting volume on ready event causes TypeError

### ISSUE THREAD

**Issue by filecage** [zohararad/audio5js#72]
When setting the volume on ready, I get a uncaught TypeError: Cannot set property 'volume' of undefined from audio5js in line 716.

I am using the unminified version 0.1.10.

**Comment by zohararad** [comment]
You need to load the audio itself before setting the volume. the ready event just means the player instance has finished initializing.

**Comment by filecage** [comment]
That's a logic thing, somehow. Is the audio setting a player-related property or an audio-related property? For me, it's a player related property and thereby I should be able to set the volume once the player is ready. In my current use case I'm using one player instance with several audio files - following the currently supported events, I have to set the volume each time an audio is ready / loaded.

That's something I can work with, but it just doesn't reflect my understanding of audio / player property distribution. If that's something discussible for you, I could try some fixes and add a pull request.

**Comment by zohararad** [comment]
The reason there's a `ready` event on the audio5 instance is to ensure the Flash engine is loaded properly and is ready to accept commands via external interface.

You should be able to set the volume only once, as the audio isn't destroyed between URL loads.
Alternatively you can capture the `canplay` event and set the volume there.

If you want to send a PR, im happy to accept a PR that allows you to define an initial audio level as part of the instance options, as long as it doesn't interfere with current logic, and sets the volume only once when the audio instances are initially created (I don't want to break peoples' code if they have other setups)

**Comment by kamijoutouma** [comment]
@filecage if you wish to make a PR then refer to my post in the link below for examples of preset volumes in a different library i modified for my friend barry. It should help you get a feel for how to make it work without interfering.
https://github.com/zohararad/audio5js/issues/56

@zohararad same as the last one ;P

**Comment by zohararad** [comment]
@kamijoutouma I'll leave this one open for a while just to wait for a PR if one is coming from @filecage

**Comment by filecage** [comment]
I've build a workaround solution in my audio wrapper (which then controls audio5js) which has been in production for a few weeks now and I haven't heard of any problems yet, so I guess that I solved this for me. Due to a lack of time I probably won't be able to fix the behaviour of audio5js (which is not the expected behaviour in my opinion) and so there won't be a PR, sorry. If I'll find some time I will dig into this.
