### ISSUE TITLE
Error when on https

### ISSUE THREAD

**Issue by iFlash** [zohararad/audio5js#73]
Hello,

I have integrated the player without problem on my site. But when I switch to https, I will get the following error when trying to load an audio:

Error: Audio Error. Failed to Load Audio

Back on http it works flawless. Any idea what I do wrong?

Best

iFlash

**Comment by zohararad** [comment]
Are you perhaps loading the audio over HTTP? You cant have mixed content (HTTPS/HTTP) when in HTTPS

**Comment by iFlash** [comment]
I found the error: It's Safari's behavior on self signed ssl certs. When I "approved" it for my machine, everything was fine. Thanks for your quick feedback.

**Comment by zohararad** [comment]
My pleasure - btw this is default on all browsers when working with self-signed SSL certs.

**Comment by kamijoutouma** [comment]
@iFlash just in case you didn't know this (even though this is close) 
for any file or link on a page if you remove the http: and just keep the //restoflink it will automatically switch to the current pages protocol Since it has no predefined protocol on it already.
