### ISSUE TITLE
one instance has issues loading multiple tracks

### ISSUE THREAD

**Issue by BryanWilhite** [zohararad/audio5js#74]
When I run your codepen sample [http://codepen.io/anon/pen/xZgExz] in Google Chrome on Windows 10 (and in IE) I am unable to play another track while one is currently playing. Exemplia: click on track 1 and let play for a few seconds then click on track 2.

**Comment by zohararad** [comment]
@BryanWilhite did you use the latest version from master?

**Comment by BryanWilhite** [comment]
Ah, now I see that your codepen sample is still using version 0.1.10 [https://cdnjs.cloudflare.com/ajax/libs/audio5js/0.1.10/audio5.min.js]; I incorrectly assumed that your codepen sample would be pointing to the lastest from master. Will I get the latest through bower so I can setup Audio5js on my Azure Blob storage? Or do I have to download the GitHub zip and manually upload to Azure?

**Comment by zohararad** [comment]
Downloading from Github and uploading to wherever would be the safest bet. I haven't updated bower / npm etc.

**Comment by BryanWilhite** [comment]
My codepen sample [http://codepen.io/rasx/pen/obBLge] has been updated with the latest from the repo. It appears that this issue is resolved.
