### ISSUE TITLE
milli seconds for progress

### ISSUE THREAD

**Issue by mtalhajamil** [zohararad/audio5js#77]
Progress returns time in seconds, It would be nice if I get milliseconds also.

**Comment by zohararad** [comment]
No can do - that's the API HTML5 exposes as far as I know

**Comment by mtalhajamil** [comment]
the ng-audio directive is also a wrapper of HTML 5 audio, but it give milli seconds

**Comment by zohararad** [comment]
@mtalhajamil I didn't write the angular demo, and it is very outdated. perhaps there is a conversion there.
from what I checked the HTML5 API is second-based rather than millisecond-based. if you need millisecond, perhaps multiplying by 1000 will do the trick?

**Comment by mtalhajamil** [comment]
yea got it thankyou
