### ISSUE TITLE
Catch HTTP response errors when loading audio?

### ISSUE THREAD

**Issue by jakemmarsh** [zohararad/audio5js#81]
I'm calling `player.load` (where `player` is my Audio5js instance) with URLs that map to my API. My API is then responsible for piping back the appropriate audio file from third-party sources. This works correctly when my API is able to find the track. However, if my API returns a 404 (or any other HTTP error status), audio5js doesn't seem to register this as an error and so nothing happens (except it continuing to be in a loading state).

I'm registering an `error` handler in the `ready` option on initialization:
```js
ready: function() {
  this.on('canplay', () => { component.setState({ buffering: false }); });
  this.on('timeupdate', component.updateProgress);
  this.on('error', (err) => {
    console.log('err in player:', err);
  });
  this.on('ended', component.nextTrack);
 this.audio.volume(component.state.volume);
}
```

All of the rest of these handlers work, but the error handler is never triggered. I've also tried wrapping the call to `player.load` in a `try/catch`, but still no luck. Is there any way to catch an error when loading audio and receiving an HTTP error? Thanks

**Comment by zohararad** [comment]
Hmmmm... it should work in theory. I can suggest that you check this in the following way:

1. Use audio files that are natively supported by your browser (so the Flash player is not selected to play the audio)
2. Make sure your server returns a 404 status but with the correct content type of the file in question
3. Maybe try a different HTTP status just for kicks (like 500) to see if that triggers an error event

If for some reason it doesn't work, you could always return an empty audio track and cause your player to skip to the next track in question.

Please let me know here what you found with the above suggestions

**Comment by jakemmarsh** [comment]
It looks like this was due to me setting the `throw_errors` option to `true`, causing the player not to trigger the error event. Although this is documented, it seems a little counter-intuitive.

Anyways, it's working now. Thanks for the quick response!
