### ISSUE TITLE
Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.

### ISSUE THREAD

**Issue by stccorp** [zohararad/audio5js#88]
I am getting the following error on Nexus 7  Android 6.0.1 on Chrome

Uncaught (in promise) DOMException: play() can only be initiated by a user gesture. audio5.js:726

My Code
    <script src="/assets/js/audio5.js"></script>
    <script>
        function initAudio () {
            var audio5js = new Audio5js({
                ready: function () {
                    this.load('/assets/alarm2.ogg');
                    this.play();
                }
            });
        }
        initAudio();
    </script>

**Comment by zohararad** [comment]
On mobile platforms some JS code can only be executed by an explicit user interaction (such as click), to prevent abuse and ensure the user actually meant to perform the action.

Try loading the audio, playing it and then pausing it immediately, and then call play again inside your promise. If that doesn't help, then you need to call the play method inside the actual event handler

**Comment by stccorp** [comment]
FYI, it works perfect on firefox android

**Comment by zohararad** [comment]
WebKit and Gecko have different rules about this, so you can't really compare the two. Did you try any of my suggestions above?

**Comment by stccorp** [comment]
The application work as a monitor and it needs to sound an alarm. I cannot
have the users clicking on  the tablet to be able to hear the sound. Since
firefox work, I will just make it a requirement to use it.  I really think
its stupid that at this late in the game that Google makes these kind of
differences  between mobile and desktop.  The whole idea is that everything
works the same.
