### ISSUE TITLE
fail to get audio duration directly

### ISSUE THREAD

**Issue by YogaLin** [zohararad/audio5js#90]
when I run "console.log(this.duration)" in audioReady, it returns 0.

**Comment by zohararad** [comment]
This isn't for video but for audio only. I need more info to help you find out what's wrong, like a code example, what file format etc.

**Comment by YogaLin** [comment]
[test-audio.zip](https://github.com/zohararad/audio5js/files/1302701/test-audio.zip)

this is my working file based on audio5js

**Comment by YogaLin** [comment]
![image](https://user-images.githubusercontent.com/11386122/30426481-ce7a539e-997e-11e7-819b-6ead72eaf73a.png)

though, it works fine in the 'timeupdate' event

**Comment by zohararad** [comment]
Ah, ok, so this is not a but but a misunderstanding.
Audio duration is only available after the audio has been loaded and started playing.

**Comment by YogaLin** [comment]
I see, so is there any way I can know the duration before I play the audio? ( I would like to show my user the length of an audio before he plays it )

**Comment by zohararad** [comment]
Nope... You need to at least load and pause it.
